### ISSUE TITLE
Bug in headlines with backticks

### ISSUE THREAD

**Issue by dferber90** [magnetikonline/markdown-toc-generate#1]
Thanks for this lovely project! It's been easy to use!

I used a headline called

```
#### `active` vs `focused`
```

And the content item generated for it resulted in

```
active` vs `focused
```

instead of 

```
`active` vs `focused`
```

which broke the formatting.

**Comment by magnetikonline** [comment]
Thanks @dferber90 !

And nicely spotted, I was intentionally removing backticks where it makes up the entire header - e.g.:

```
## `this is all a code block`
```

But this of course was breaking your use case - have updated to now only remove start/end ticks if they are the _only_ ticks in the heading... meaning your above cases should now work.

This was added in 9bc1dd73ffe17ec88b71eaed5147e115c8b6f1ac.

Thanks again.

**Comment by dferber90** [comment]
Thanks! Sweet 👍
